{
 "title": "PTP -Telemetry",
 "time": { "from": "2026-01-20T14:17:52.782Z", "to": "2026-01-20T14:27:52.782Z" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "switch",
    "query": {
     "query": "import \"influxdata/influxdb/schema\"\r\n\r\nschema.tagValues(\r\n  bucket: \"nxos_dialout\",\r\n  tag: \"source\",\r\n  predicate: (r) => r.tag1 == \"mdt_dialout\",\r\n  start: -30d\r\n)\r\n"
    }
   },
   {
    "name": "interface",
    "query": {
     "query": "import \"influxdata/influxdb/schema\"\r\n\r\nschema.tagValues(\r\n  bucket: \"nxos_dialout\",\r\n  tag: \"if_name\",\r\n  predicate: (r) => r.tag1 == \"mdt_dialout\" and r.source =~ /^${switch:regex}$/,\r\n  start: -30d\r\n)\r\n"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Mean Path Delay",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Cisco-IOS-XE-switch-ptp-oper:switch-ptp-oper-data/switch-ptp-clock-data",
     "query": "from(bucket: \"nxos_dialout\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n\r\n  |> filter(fn: (r) => r.tag1 == \"mdt_dialout\")\r\n  |> filter(fn: (r) => r.source =~ /^${switch:regex}$/)\r\n\r\n  |> filter(fn: (r) => r._measurement == \"Cisco-IOS-XE-switch-ptp-oper:switch-ptp-oper-data/switch-ptp-clock-data\")\r\n  |> filter(fn: (r) => r._field == \"clock_current_data_val/mean_path_delay/nano_seconds\")\r\n\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n",
     "select": [
      [
       {
        "params": [
         "clock_current_data_val/mean_path_delay/nano_seconds"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$switch$/" }
     ]
    }
   ]
  },
  {
   "title": "Offset",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Cisco-IOS-XE-switch-ptp-oper:switch-ptp-oper-data/switch-ptp-clock-data",
     "query": "from(bucket: \"nxos_dialout\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.tag1 == \"mdt_dialout\")\r\n  |> filter(fn: (r) => r.source =~ /^${switch:regex}$/)\r\n  |> filter(fn: (r) => r._measurement == \"Cisco-IOS-XE-switch-ptp-oper:switch-ptp-oper-data/switch-ptp-clock-data\")\r\n  |> filter(fn: (r) => r._field == \"clock_current_data_val/offset_from_master/nano_seconds\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n",
     "select": [
      [
       {
        "params": [
         "clock_current_data_val/offset_from_master/nano_seconds"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$switch$/" }
     ]
    }
   ]
  },
  {
   "title": "GrandMaster",
   "type": "stat",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "hex" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "Cisco-IOS-XE-switch-ptp-oper:switch-ptp-oper-data/switch-ptp-parent-data",
     "query": "from(bucket: \"nxos_dialout\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.tag1 == \"mdt_dialout\")\r\n  |> filter(fn: (r) => r.source =~ /^${switch:regex}$/)\r\n  |> filter(fn: (r) => r._measurement == \"Cisco-IOS-XE-switch-ptp-oper:switch-ptp-oper-data/switch-ptp-parent-data\")\r\n  |> filter(fn: (r) => r._field == \"grandmaster_identity\")\r\n  |> last()",
     "select": [
      [
       { "params": [ "grandmaster_identity" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$switch$/" }
     ]
    }
   ]
  },
  {
   "title": "changes in GrandMaster over time ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 11, "y": 8 },
   "targets": [
    {
     "alias": "GM Change",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Cisco-IOS-XE-switch-ptp-oper:switch-ptp-oper-data/switch-ptp-parent-data",
     "query": "from(bucket: \"nxos_dialout\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.tag1 == \"mdt_dialout\")\r\n  |> filter(fn: (r) => r.source =~ /^${switch:regex}$/)\r\n  |> filter(fn: (r) => r._measurement == \"Cisco-IOS-XE-switch-ptp-oper:switch-ptp-oper-data/switch-ptp-parent-data\")\r\n  |> filter(fn: (r) => r._field == \"grandmaster_identity\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n",
     "select": [
      [
       { "params": [ "grandmaster_identity" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$switch$/" }
     ]
    }
   ]
  },
  {
   "title": "Device Type",
   "type": "stat",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "Cisco-IOS-XE-switch-ptp-oper:switch-ptp-oper-data/switch-ptp-clock-data",
     "query": "from(bucket: \"nxos_dialout\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.tag1 == \"mdt_dialout\")\r\n  |> filter(fn: (r) => r.source =~ /${switch:regex}/)\r\n  |> filter(fn: (r) => r._measurement == \"Cisco-IOS-XE-switch-ptp-oper:switch-ptp-oper-data/switch-ptp-clock-data\")\r\n  |> filter(fn: (r) => r._field == \"clock_default_data_val/ptp_device_type\")\r\n  |> group()                       // collapse all tag groups\r\n  |> last()\r\n  |> keep(columns: [\"_value\"])     // only return the value column\r\n",
     "select": [
      [
       {
        "params": [
         "clock_default_data_val/ptp_device_type"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$switch$/" }
     ]
    }
   ]
  },
  {
   "title": "Delay Mechaism (currently Broken on 9200CX)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 11, "x": 11, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "Cisco-IOS-XE-switch-ptp-oper:switch-ptp-oper-data/switch-ptp-clock-data",
     "query": "from(bucket: \"nxos_dialout\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.tag1 == \"mdt_dialout\")\r\n  |> filter(fn: (r) => r.source =~ /^${switch:regex}$/)\r\n  |> filter(fn: (r) => r._measurement == \"Cisco-IOS-XE-switch-ptp-oper:switch-ptp-oper-data/switch-ptp-clock-data\")\r\n  |> filter(fn: (r) => r._field == \"ptp_oper_domain_cfg_data/delay_mechanism\")\r\n  |> last()\r\n",
     "select": [
      [
       {
        "params": [
         "ptp_oper_domain_cfg_data/delay_mechanism"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$switch$/" }
     ]
    }
   ]
  },
  {
   "title": "Total PTP Ports",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "Cisco-IOS-XE-switch-ptp-oper:switch-ptp-oper-data/switch-ptp-clock-data",
     "query": "from(bucket: \"nxos_dialout\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.tag1 == \"mdt_dialout\")\r\n  |> filter(fn: (r) => r.source =~ /^${switch:regex}$/)\r\n  |> filter(fn: (r) => r._measurement == \"Cisco-IOS-XE-switch-ptp-oper:switch-ptp-oper-data/switch-ptp-clock-data\")\r\n  |> filter(fn: (r) => r._field == \"clock_default_data_val/num_ptp_ports\")\r\n  |> last()\r\n",
     "select": [
      [
       {
        "params": [
         "clock_default_data_val/num_ptp_ports"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$switch$/" }
     ]
    }
   ]
  },
  {
   "title": "PTP Transport",
   "type": "stat",
   "gridPos": { "h": 7, "w": 11, "x": 11, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "Cisco-IOS-XE-switch-ptp-oper:switch-ptp-oper-data/switch-ptp-clock-data",
     "query": "from(bucket: \"nxos_dialout\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.tag1 == \"mdt_dialout\")\r\n  |> filter(fn: (r) => r.source =~ /^${switch:regex}$/)\r\n  |> filter(fn: (r) => r._measurement == \"Cisco-IOS-XE-switch-ptp-oper:switch-ptp-oper-data/switch-ptp-clock-data\")\r\n  |> filter(fn: (r) => r._field == \"ptp_oper_domain_cfg_data/transport_protocol\")\r\n  |> last()\r\n",
     "select": [
      [
       {
        "params": [
         "ptp_oper_domain_cfg_data/transport_protocol"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$switch$/" }
     ]
    }
   ]
  },
  {
   "title": "Event Msg - DSCP",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "Cisco-IOS-XE-switch-ptp-oper:switch-ptp-oper-data/switch-ptp-clock-data",
     "query": "from(bucket: \"nxos_dialout\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.tag1 == \"mdt_dialout\")\r\n  |> filter(fn: (r) => r.source =~ /^${switch:regex}$/)\r\n  |> filter(fn: (r) => r._measurement == \"Cisco-IOS-XE-switch-ptp-oper:switch-ptp-oper-data/switch-ptp-clock-data\")\r\n  |> filter(fn: (r) => r._field == \"ptp_oper_domain_cfg_data/dscp_event\")\r\n  |> last()\r\n",
     "select": [
      [
       {
        "params": [
         "ptp_oper_domain_cfg_data/dscp_event"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$switch$/" }
     ]
    }
   ]
  },
  {
   "title": "PTP Profile",
   "type": "stat",
   "gridPos": { "h": 6, "w": 9, "x": 6, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "Cisco-IOS-XE-switch-ptp-oper:switch-ptp-oper-data/switch-ptp-clock-data",
     "query": "from(bucket: \"nxos_dialout\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.tag1 == \"mdt_dialout\")\r\n  |> filter(fn: (r) => r.source =~ /^${switch:regex}$/)\r\n  |> filter(fn: (r) => r._measurement == \"Cisco-IOS-XE-switch-ptp-oper:switch-ptp-oper-data/switch-ptp-clock-data\")\r\n  |> filter(fn: (r) => r._field == \"clock_default_data_val/profile\")\r\n  |> last()\r\n",
     "select": [
      [
       { "params": [ "clock_default_data_val/profile" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$switch$/" }
     ]
    }
   ]
  },
  {
   "title": "General Msg - DSCP",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 15, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "Cisco-IOS-XE-switch-ptp-oper:switch-ptp-oper-data/switch-ptp-clock-data",
     "query": "from(bucket: \"nxos_dialout\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.tag1 == \"mdt_dialout\")\r\n  |> filter(fn: (r) => r.source =~ /^${switch:regex}$/)\r\n  |> filter(fn: (r) => r._measurement == \"Cisco-IOS-XE-switch-ptp-oper:switch-ptp-oper-data/switch-ptp-clock-data\")\r\n  |> filter(fn: (r) => r._field == \"ptp_oper_domain_cfg_data/dscp_general\")\r\n  |> last()\r\n",
     "select": [
      [
       {
        "params": [
         "ptp_oper_domain_cfg_data/dscp_general"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$switch$/" }
     ]
    }
   ]
  },
  {
   "title": "PTP State",
   "type": "table",
   "gridPos": { "h": 18, "w": 22, "x": 0, "y": 35 },
   "targets": [
    {
     "measurement": "Cisco-IOS-XE-switch-ptp-oper:switch-ptp-oper-data/switch-ptp-port-data",
     "query": "from(bucket: \"nxos_dialout\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.tag1 == \"mdt_dialout\")\r\n  |> filter(fn: (r) => r.source == \"$switch\")\r\n  |> filter(fn: (r) => r._measurement == \"Cisco-IOS-XE-switch-ptp-oper:switch-ptp-oper-data/switch-ptp-port-data\")\r\n  |> filter(fn: (r) => r._field == \"port_state\")\r\n\r\n  // group only to get last per interface\r\n  |> group(columns: [\"if_name\"])\r\n  |> last()\r\n\r\n  // UNGROUP → collapse back into one table\r\n  |> group()\r\n\r\n  |> keep(columns: [\"_time\", \"source\", \"if_name\", \"_value\"])\r\n  |> rename(columns: {_value: \"port_state\"})\r\n  |> sort(columns: [\"if_name\"])\r\n",
     "select": [
      [
       { "params": [ "port_state" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$switch$/" }
     ]
    }
   ]
  }
 ]
}